[package]
name = "inklang_json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1" }
inklang_json_macro = { version = "0.1", path = "../json_macro" }
